baseURL = "https://alcinaengineering.co.uk/"
languageCode = "en-gb"
title = "Alcina Engineering Limited"
theme = "massively"
googleanalytics = "UA-5357036-9"

[params]
    custom_css = ["/css/overrides.css"]
    favicon = "/images/favicon.ico"

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "false"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = -100

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/#footer"
    weight = 100
