# docker run --name alcina -e VIRTUAL_HOST=alcinaengineering.co.uk,www.alcinaengineering.co.uk -e LETSENCRYPT_HOST=alcinaengineering.co.uk,www.alcinaengineering.co.uk -e LETSENCRYPT_EMAIL=smirlie@googlemail.com -v /opt/alcina/:/usr/share/nginx/html:ro -d nginx

version: '3.1'
services:
  alcina:
    image: registry.smirlwebs.com/smirl/alcina:2.2.0
    environment:
      API_KEY: 'c312f9639417764ef437fed52eb4a402'
      AMPLIFY_IMAGENAME: 'alcinaengineering'
    networks:
     - proxy
    deploy:
      replicas: 1
      labels:
       - com.df.notify=true
       - com.df.distribute=true
       - com.df.httpsOnly=true
       - com.df.srcPort.1=443
       - com.df.srcPort.2=80
       - com.df.port=80
       - com.df.serviceDomain=alcinaengineering.co.uk,www.alcinaengineering.co.uk
       - com.df.letsencrypt.host=alcinaengineering.co.uk,www.alcinaengineering.co.uk
       - com.df.letsencrypt.email=smirlie@googlemail.com

networks:
  proxy:
    external: true
