---
apiVersion: v1
kind: Namespace
metadata:
  name: alcinaengineering
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: alcinaengineering
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions
  namespace: alcinaengineering
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions
  namespace: alcinaengineering
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-actions
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: alcinaengineering
